### PR TITLE
Update simple-wireplumber-gui runtime to 46

### PR DESCRIPTION
**Pull request by ghost**
- Update simple-wireplumber-gui runtime to 46 since runtime version 44 has reached end-of-life.
- Fix appdata issues.

### CODE REVIEW

**Comment by ghost** [comment]
```
{
    "errors": [
        "appstream-failed-validation"
    ],
    "warnings": [
        "appstream-name-too-long"
    ],
    "appstream": [
        "E: io.github.dyegoaurelio.simple-wireplumber-gui.desktop:5: cid-rdns-contains-hyphen"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

**Comment by bbhtt** [comment]
> io.github.dyegoaurelio.simple-wireplumber-gui.desktop

Remove `.desktop` from id tag and add `io.github.dyegoaurelio.simple-wireplumber-gui.desktop` to `provides` tag.

**Comment by ghost** [comment]
@dyegoaurelio I've updated simple-wireplumber-gui runtime to 46 since runtime version 44 has reached end-of-life. Could you review changes? Thanks.

**Comment by ghost** [comment]
> > io.github.dyegoaurelio.simple-wireplumber-gui.desktop
> 
> Remove `.desktop` from id tag and add `io.github.dyegoaurelio.simple-wireplumber-gui.desktop` to `provides` tag.

Do I also need to add the `replaces` tag?


> If a rename is necessary, please add the old [ID tag](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#id) as a [provides tag](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#provides) and a [replaces tag](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#replaces) in the [MetaInfo file](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#path-and-filename).

https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#renaming-id-tag

**Comment by bbhtt** [comment]
If you can that'd be nice.

**Comment by bbhtt** [comment]
bot, build

**Pull request merged**
